[program:vidgaze-schedule-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/html/artisan schedule:run --verbose --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/etc/supervisor/logs/worker.log
stopwaitsecs=900
cron=* * * * *
