<?php

use App\Helpers\PlatformAPIs\AuthDailymotion;
use App\Helpers\PlatformAPIs\AuthTwitch;
use App\Helpers\PlatformAPIs\AuthVimeo;
use App\Helpers\PlatformAPIs\AuthYouTube;
use App\Helpers\PlatformAPIs\BitChute;
use App\Helpers\PlatformAPIs\Dailymotion;
use App\Helpers\PlatformAPIs\FaceBook;
use App\Helpers\PlatformAPIs\Instagram;
use App\Helpers\PlatformAPIs\Odysee;
use App\Helpers\PlatformAPIs\Podcasts;
use App\Helpers\PlatformAPIs\Rumble;
use App\Helpers\PlatformAPIs\TikTok;
use App\Helpers\PlatformAPIs\Twitch;
use App\Helpers\PlatformAPIs\Vimeo;
use App\Helpers\PlatformAPIs\YouTube;

/**
 * Single source of truth for platform identity, capabilities, and wiring.
 *
 * Keys MUST match App\Enums\Platform backed values (e.g. youtube, rumble).
 * Tiers: A = full creator stack where APIs allow, B = view/discovery, C = stub/reserved, D = hidden/off.
 */
return [
    'vidgaze' => [
        'tier' => 'D',
        'label' => 'VidGaze',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => false,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => null,
        'frontend_player' => null,
        'integration_notes' => 'Native app; not an external link target.',
    ],
    'youtube' => [
        'tier' => 'A',
        'label' => 'YouTube',
        'studio_connect' => true,
        'link_type' => 'oauth',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => true,
        'stream_source' => true,
        'auth_class' => AuthYouTube::class,
        'platform_class' => YouTube::class,
        'frontend_player' => 'YouTube',
        'integration_notes' => 'Google OAuth; Data API for sync and upload.',
    ],
    'dailymotion' => [
        'tier' => 'A',
        'label' => 'Dailymotion',
        'studio_connect' => true,
        'link_type' => 'oauth',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => AuthDailymotion::class,
        'platform_class' => Dailymotion::class,
        'frontend_player' => 'Dailymotion',
        'integration_notes' => 'OAuth; upload gated off in registry until DM uploader is enabled.',
    ],
    'vimeo' => [
        'tier' => 'A',
        'label' => 'Vimeo',
        'studio_connect' => true,
        'link_type' => 'oauth',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => true,
        'stream_source' => false,
        'auth_class' => AuthVimeo::class,
        'platform_class' => Vimeo::class,
        'frontend_player' => 'Vimeo',
        'integration_notes' => 'Vimeo OAuth + upload.',
    ],
    'twitch' => [
        'tier' => 'A',
        'label' => 'Twitch',
        'studio_connect' => true,
        'link_type' => 'oauth',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => false,
        'stream_source' => true,
        'auth_class' => AuthTwitch::class,
        'platform_class' => Twitch::class,
        'frontend_player' => 'Twitch',
        'integration_notes' => 'Helix OAuth; live streams.',
    ],
    'rumble' => [
        'tier' => 'B',
        'label' => 'Rumble',
        'studio_connect' => true,
        'link_type' => 'claim',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => Rumble::class,
        'frontend_player' => 'Rumble',
        'integration_notes' => 'Discovery via Apify scraper; claim channel by slug (no OAuth in app).',
    ],
    'facebook' => [
        'tier' => 'C',
        'label' => 'Facebook',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => false,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => FaceBook::class,
        'frontend_player' => null,
        'integration_notes' => 'Video source enum only; Apify placeholder, no Studio link until Meta policy work.',
    ],
    'odysee' => [
        'tier' => 'B',
        'label' => 'Odysee',
        'studio_connect' => true,
        'link_type' => 'claim',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => Odysee::class,
        'frontend_player' => 'Odysee',
        'integration_notes' => 'Lighthouse search; claim channel handle (matches odysee.com/@Handle — store without @).',
    ],
    'podcasts' => [
        'tier' => 'C',
        'label' => 'Podcasts',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => true,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => Podcasts::class,
        'frontend_player' => null,
        'integration_notes' => 'Separate content model; reserved enum.',
    ],
    'soundcloud' => [
        'tier' => 'C',
        'label' => 'SoundCloud',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => false,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => null,
        'frontend_player' => null,
        'integration_notes' => 'Reserved; not wired.',
    ],
    'spotify' => [
        'tier' => 'C',
        'label' => 'Spotify',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => false,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => null,
        'frontend_player' => null,
        'integration_notes' => 'Config stub only; music routes commented.',
    ],
    'instagram' => [
        'tier' => 'C',
        'label' => 'Instagram',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => false,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => Instagram::class,
        'frontend_player' => null,
        'integration_notes' => 'Search stub; Meta linking TBD.',
    ],
    'tiktok' => [
        'tier' => 'C',
        'label' => 'TikTok',
        'studio_connect' => false,
        'link_type' => null,
        'supported_for_video_index' => false,
        'unified_search' => false,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => TikTok::class,
        'frontend_player' => null,
        'integration_notes' => 'Enum + stub; developer program required for OAuth.',
    ],
    'bitchute' => [
        'tier' => 'C',
        'label' => 'BitChute',
        'studio_connect' => true,
        'link_type' => 'claim',
        'supported_for_video_index' => true,
        'unified_search' => true,
        'uploadable' => false,
        'stream_source' => false,
        'auth_class' => null,
        'platform_class' => BitChute::class,
        'frontend_player' => 'BitChute',
        'integration_notes' => 'Claim by channel name (e.g. from bitchute.com/channel/...). Search uses Firecrawl (site: queries + scrape enrich); requires services.firecrawl API key.',
    ],
];
