[unix_http_server]
file=/var/run/supervisor-workers.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord-workers.log
pidfile=/var/run/supervisord-workers.pid

[include]
files = /var/www/html/docker/8.4/vidgaze-workers/*.conf
