name: "Staging Release"

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: ConfigureAWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.VIDGAZE_AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.VIDGAZE_AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1


      - name: Login to AmazonECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: docker build
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: vidgaze-laravel-app
          IMAGE_TAG: "latest"

        run: |
          export WWWUSER=${WWWUSER:-$UID}
          export WWWGROUP=${WWWGROUP:-$(id -g)}
          docker-compose -f docker-compose-prod.yml build
          docker tag vidgaze-prod/app ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
